apiVersion: v1
kind: Service
metadata: 
    name: k8s-pdsmanagement-service
spec:
    selector:
        app: k8s-pdsmanagement
    ports:
        - port: 8181
          targetPort: 8181
          nodePort: 30036
          protocol: TCP
    type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-pdsmanagement-deployment
  labels:
    app: k8s-pdsmanagement
spec:
  selector:
    matchLabels:
      app: k8s-pdsmanagement
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-pdsmanagement
    spec:
      containers:
        - name: k8s-pdsmanagement
          image: gswain3316/pdsmanagement:latest
          ports:
            - containerPort: 8181
